package nativego

import (
 "bytes"
 "context"
 "encoding/binary"
 "errors"
 "io"
 "net"
 "net/netip"
 "time"
)

// DatagramSession is an authenticated, in-process Go UDP-over-stream tunnel.
// One session belongs to exactly one destination; replies for any other
// destination fail closed instead of being injected into the packet stack.
type DatagramSession struct {
 conn net.Conn
 target netip.AddrPort
 protocol string
}

func (s *DatagramSession) Close() error { return s.conn.Close() }

// DialDatagram opens a protected, certificate-verified raw TLS carrier.
// Only the two already-implemented Go-native protocol subsets are admitted.
// In particular REALITY, Vision, WS and unsupported ciphers NEVER downgrade.
func (d *Dialer) DialDatagram(ctx context.Context, target netip.AddrPort) (*DatagramSession, error) {
 if d==nil || d.protected==nil {return nil,ErrUnprotected}
 if !target.IsValid() || target.Port()==0 {return nil,errors.New("nativego: invalid UDP destination")}
 conn,err:=d.secureCarrier(ctx)
 if err!=nil{return nil,err}
 if d.node.Transport=="websocket"{
  wrapped,e:=openWebSocket(ctx,conn,d.node)
  if e!=nil{_=conn.Close();return nil,e}
  conn=wrapped
 }
 var initial []byte
 switch d.node.Protocol {
 case "vless":
  initial=vlessUDPRequest(d.uuid,target)
 case "trojan":
  initial=trojanUDPRequest(d.passwordHash,target)
 default:
  _=conn.Close();return nil,ErrUnsupported
 }
 if err=writeFull(conn,initial);err!=nil{_=conn.Close();return nil,err}
 var authenticated net.Conn=conn
 if d.node.Protocol=="vless"{authenticated=&vlessResponseConn{Conn:conn}}
 return &DatagramSession{conn:authenticated,target:target,protocol:d.node.Protocol},nil
}

func vlessUDPRequest(id [16]byte,target netip.AddrPort)[]byte {
 out:=vlessRequest(id,target)
 out[18]=2 // VLESS command byte: TCP=1, UDP=2
 return out
}
func trojanUDPRequest(passwordHash string,target netip.AddrPort)[]byte {
 out:=trojanRequest(passwordHash,target)
 out[len(passwordHash)+2]=3 // Trojan command byte: TCP=1, UDP=3
 return out
}

// WriteDatagram preserves the UDP record boundary and checks the IP-family
// limit before any write. TLS writes may be partial; writeFull handles that.
func (s *DatagramSession) WriteDatagram(payload []byte)error {
 max:=65507
 if s.target.Addr().Is6(){max=65527}
 if len(payload)>max{return errors.New("nativego: oversized UDP payload")}
 var wire []byte
 switch s.protocol {
 case "vless":
  wire=make([]byte,2+len(payload))
  binary.BigEndian.PutUint16(wire[:2],uint16(len(payload)))
  copy(wire[2:],payload)
 case "trojan":
  address:=destinationBytes(s.target)
  wire=make([]byte,0,len(address)+len(payload)+4)
  wire=append(wire,address[2])
  wire=append(wire,address[3:]...)
  wire=append(wire,address[:2]...)
  wire=append(wire,byte(len(payload)>>8),byte(len(payload)),'\r','\n')
  wire=append(wire,payload...)
 default:
  return ErrUnsupported
 }
 return writeFull(s.conn,wire)
}

// ReadDatagram accepts exactly one complete UDP record and validates the
// authenticated destination in Trojan replies. Never return a partial record.
func(s *DatagramSession) ReadDatagram()([]byte,error){
 var length [2]byte
 switch s.protocol {
 case "vless":
  if _,err:=io.ReadFull(s.conn,length[:]);err!=nil{return nil,err}
 case "trojan":
  var kind [1]byte
  if _,err:=io.ReadFull(s.conn,kind[:]);err!=nil{return nil,err}
  addressLen:=0
  switch kind[0] {
  case 1:addressLen=4
  case 4:addressLen=16
  case 3:
   // Domain destinations are not generated by the fixed-IP gVisor flow.
   // Fail closed rather than accept a reply from an unverified endpoint.
   return nil,errors.New("nativego: unexpected UDP reply address type")
  default:return nil,errors.New("nativego: invalid UDP reply address type")
  }
  address:=make([]byte,addressLen+2)
  if _,err:=io.ReadFull(s.conn,address);err!=nil{return nil,err}
  ip,ok:=netip.AddrFromSlice(address[:addressLen])
  port:=binary.BigEndian.Uint16(address[addressLen:])
  if !ok || netip.AddrPortFrom(ip,port)!=s.target {
   return nil,errors.New("nativego: UDP reply destination mismatch")
  }
  if _,err:=io.ReadFull(s.conn,length[:]);err!=nil{return nil,err}
  var delimiter [2]byte
  if _,err:=io.ReadFull(s.conn,delimiter[:]);err!=nil{return nil,err}
  if !bytes.Equal(delimiter[:],[]byte{'\r','\n'}){return nil,errors.New("nativego: Trojan UDP delimiter mismatch")}
 default:return nil,ErrUnsupported
 }
 size:=int(binary.BigEndian.Uint16(length[:]))
 max:=65507
 if s.target.Addr().Is6(){max=65527}
 if size>max{return nil,errors.New("nativego: oversized UDP response")}
 out:=make([]byte,size)
 if _,err:=io.ReadFull(s.conn,out);err!=nil{return nil,err}
 return out,nil
}

// Bound blocking reads and writes to avoid retaining a stopped flow forever.
// The timeout is refreshed by the UDP worker for every successfully processed
// record, and close interrupts an outstanding operation.
func(s *DatagramSession) readDeadline()error{return s.conn.SetReadDeadline(time.Now().Add(30*time.Second))}
func(s *DatagramSession) writeDeadline()error{return s.conn.SetWriteDeadline(time.Now().Add(10*time.Second))}
