#pragma once
#include "json.hpp"
#include <set>

namespace vpn {
inline std::string uri_decode(const std::string& s){std::string o;for(size_t i=0;i<s.size();++i){if(s[i]=='%'&&i+2<s.size()&&hex_digit(s[i+1])>=0&&hex_digit(s[i+2])>=0){o+=char(hex_digit(s[i+1])*16+hex_digit(s[i+2]));i+=2;}else o+=s[i];}return o;}
inline Bytes b64_decode(std::string s){s=uri_decode(s);Bytes o;uint32_t bits=0;unsigned n=0;const std::string alphabet="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    for(char c:s){if(c=='=')break;if(c=='-')c='+';if(c=='_')c='/';auto p=alphabet.find(c);if(p==std::string::npos)continue;bits=(bits<<6)|uint32_t(p);n+=6;if(n>=8){n-=8;o.push_back(uint8_t(bits>>n));}}return o;}
inline std::string b64_encode(const Bytes& in){const char* a="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";std::string o;for(size_t i=0;i<in.size();i+=3){uint32_t v=uint32_t(in[i])<<16;if(i+1<in.size())v|=uint32_t(in[i+1])<<8;if(i+2<in.size())v|=in[i+2];o+=a[v>>18];o+=a[(v>>12)&63];o+=i+1<in.size()?a[(v>>6)&63]:'=';o+=i+2<in.size()?a[v&63]:'=';}return o;}
inline std::string from_bytes(const Bytes& b){return std::string(b.begin(),b.end());}
inline Bytes to_bytes(const std::string& s){return Bytes(s.begin(),s.end());}
using Options=std::map<std::string,std::string>;
inline Options uri_query(const std::string& s){Options q;std::istringstream in(s);std::string item;while(std::getline(in,item,'&')){auto eq=item.find('=');if(eq==std::string::npos)continue;q.emplace(lower(uri_decode(item.substr(0,eq))),uri_decode(item.substr(eq+1)));}return q;}
inline std::string option(const Options& q,std::initializer_list<const char*> keys,const std::string& d=""){for(auto k:keys){auto i=q.find(k);if(i!=q.end())return i->second;}return d;}
inline bool present(const Options& q,std::initializer_list<const char*> keys){for(auto k:keys)if(q.count(k))return true;return false;}
inline bool true_value(std::string v){v=lower(v);return v=="1"||v=="true"||v=="yes"||v=="on";}
inline std::string transport_name(std::string v){auto k=lower(trim(v));if(k=="mkcp"||k=="kcp")return "kcp";if(k.empty()||k=="tcp"||k=="raw")return "raw";if(k=="http"||k=="h2"||k=="http2")return "http";if(k=="ws"||k=="websocket")return "websocket";if(k=="gun"||k=="grpc")return "grpc";if(k=="splithttp"||k=="xhttp")return "xhttp";if(k=="http-upgrade"||k=="httpupgrade")return "httpupgrade";return trim(v);}
inline std::string security_name(std::string v){auto k=lower(trim(v));if(k=="1"||k=="true"||k=="on"||k=="tls")return "tls";if(k.empty()||k=="0"||k=="false"||k=="off"||k=="none")return "none";if(k=="reality")return "reality";if(k=="xtls")return "xtls";return trim(v);}
inline Options raw_uri_query(const std::string& s){Options q;std::istringstream in(s);std::string item;while(std::getline(in,item,'&')){auto eq=item.find('=');if(eq!=std::string::npos)q.emplace(lower(uri_decode(item.substr(0,eq))),item.substr(eq+1));}return q;}
inline std::string form_field(std::string raw){std::replace(raw.begin(),raw.end(),'+',' ');return uri_decode(raw);}
inline std::string enum_field(const Options& raw,const Options& decoded,std::initializer_list<const char*> keys,bool transport){auto value=option(decoded,keys);auto source=option(raw,keys);if(source.find('+')==std::string::npos)return value;auto candidate=form_field(source);auto canonical=transport?transport_name(candidate):security_name(candidate);const std::set<std::string> networks{"raw","websocket","httpupgrade","grpc","xhttp","http","kcp","quic","domainsocket","ds","meek","hysteria","hysteria2"};const std::set<std::string> security{"none","tls","reality","xtls"};return (transport?networks:security).count(canonical)?candidate:value;}
inline Json optional_json(const std::string& decoded,const std::string& raw){if(trim(decoded).empty())return Json();try{return json_parse(decoded);}catch(...){if(raw.find('+')!=std::string::npos){try{auto j=json_parse(form_field(raw));if(j.kind==Json::Object)return j;}catch(...){}}return Json(decoded);}}
struct Config {
    std::string server,tls_name,password_hash,password,protocol="trojan",transport="raw",security="tls",cipher,flow,fingerprint,path="/",host_header,service,authority,mode,header_type="none",encryption="none",public_key,short_id,spider_x,ech;
    std::vector<std::string> alpn;Options original_options;Json extra,finalmask;
    std::array<uint8_t,16> uuid{};bool legacy_insecure_requested=false,explicit_sni=false;
    uint16_t port=443,listen_port=1080;unsigned connect_ms=10000,idle_ms=60000,max_connections=32,alter_id=0,ws_early_data=0;
    std::string ws_early_header="Sec-WebSocket-Protocol",ss_plugin,ss_plugin_mode;bool ss_plugin_mux=false,ws_path_ed_invalid=false;
    std::string test_ca_file,tls_ca_file,ready_file;
};
inline Bytes digest(const std::string& algorithm,const Bytes& data);
inline std::array<uint8_t,16> uuid_bytes(std::string s){std::array<uint8_t,16> b{};if(!s.empty()&&s.size()<=30){Bytes name(16);auto text=to_bytes(s);name.insert(name.end(),text.begin(),text.end());auto hash=digest("sha1",name);std::copy_n(hash.begin(),16,b.begin());b[6]=uint8_t((b[6]&15)|0x50);b[8]=uint8_t((b[8]&63)|0x80);return b;}s.erase(std::remove(s.begin(),s.end(),'-'),s.end());if(s.size()!=32)throw std::runtime_error("PARSE_INVALID: UUID must have 16 bytes");for(size_t i=0;i<16;++i){int a=hex_digit(s[2*i]),d=hex_digit(s[2*i+1]);if(a<0||d<0)throw std::runtime_error("PARSE_INVALID: invalid UUID");b[i]=uint8_t(a*16+d);}return b;}
inline void endpoint(Config& c,std::string s){auto slash=s.find('/');if(slash!=std::string::npos)s.resize(slash);std::string p;
    if(!s.empty()&&s[0]=='['){auto close=s.find(']');if(close==std::string::npos||close+1>=s.size()||s[close+1]!=':')throw std::runtime_error("PARSE_INVALID: invalid IPv6 endpoint");c.server=s.substr(1,close-1);p=s.substr(close+2);}else{auto colon=s.rfind(':');if(colon==std::string::npos||colon!=s.find(':'))throw std::runtime_error("PARSE_INVALID: endpoint requires host and port");c.server=s.substr(0,colon);p=s.substr(colon+1);}check_host(c.server);c.port=uint16_t(number(p,1,65535));}
inline Options sip003_options(const std::string& text){Options out;std::string item;bool escaped=false;auto add=[&]{auto equal=item.find('=');auto name=lower(trim(item.substr(0,equal)));if(!name.empty()&&!out.emplace(name,equal==std::string::npos?"":item.substr(equal+1)).second)throw std::runtime_error("PARSE_INVALID: duplicate plugin option");item.clear();};for(char ch:text){if(escaped){item+=ch;escaped=false;}else if(ch=='\\')escaped=true;else if(ch==';')add();else item+=ch;}if(escaped)throw std::runtime_error("PARSE_INVALID: plugin escape");add();return out;}
inline void parse_ss_plugin(Config& c){if(c.protocol!="ss")return;auto value=option(c.original_options,{"plugin"});if(value.empty()||std::set<std::string>{"none","0","false","off"}.count(lower(trim(value))))return;if(lower(value).find("v2ray-plugin%3b")==0){auto candidate=uri_decode(value);auto split=candidate.find(';');auto opts=sip003_options(candidate.substr(split+1));const std::set<std::string> allowed{"mode","host","path","tls","mux","sni","skip-cert-verify"};bool valid=true;for(const auto& p:opts)valid=valid&&allowed.count(p.first);if(opts.count("mode"))valid=valid&&opts.at("mode")=="websocket";if(opts.count("tls"))valid=valid&&opts.at("tls").empty();if(opts.count("skip-cert-verify"))valid=valid&&std::set<std::string>{"1","0","true","false"}.count(opts.at("skip-cert-verify"));if(opts.count("mux")){try{(void)number(opts.at("mux"),0,1024);}catch(...){valid=false;}}if(valid)value=candidate;}
    auto end=value.find(';');c.ss_plugin=lower(trim(value.substr(0,end)));for(unsigned char ch:c.ss_plugin)if(!((ch>='a'&&ch<='z')||(ch>='0'&&ch<='9')||ch=='-'||ch=='_'))throw std::runtime_error("PARSE_INVALID: plugin name");if(std::set<std::string>{"none","0","false","off"}.count(c.ss_plugin)){c.ss_plugin.clear();return;}if(c.ss_plugin!="v2ray-plugin")return;auto opts=sip003_options(end==std::string::npos?"":value.substr(end+1));if(true_value(option(opts,{"skip-cert-verify"})))c.legacy_insecure_requested=true;c.ss_plugin_mode=lower(option(opts,{"mode"},"websocket"));if(c.ss_plugin_mode!="websocket")return;c.transport="websocket";c.path=option(opts,{"path"},"/");c.host_header=option(opts,{"host"},"cloudfront.com");check_host(c.host_header);if(opts.count("tls")){c.security="tls";c.tls_name=c.host_header;c.explicit_sni=true;}auto mux=option(opts,{"mux"},"1");try{c.ss_plugin_mux=number(mux,0,1024)!=0;}catch(...){throw std::runtime_error("PARSE_INVALID: plugin mux");}}
inline void parse_uri(Config& c,std::string uri){if(uri.size()>65536)throw std::runtime_error("PARSE_INVALID: URI too large");auto split=uri.find("://");if(split==std::string::npos)throw std::runtime_error("PARSE_INVALID: missing scheme");c.protocol=lower(uri.substr(0,split));if(c.protocol!="vless"&&c.protocol!="vmess"&&c.protocol!="trojan"&&c.protocol!="ss")throw std::runtime_error("PARSE_INVALID: unknown protocol");
    uri=uri.substr(split+3);auto fragment=uri.find('#');if(fragment!=std::string::npos)uri.resize(fragment);Options q,raw_q;bool legacy=c.protocol=="vmess"&&uri.find('@')==std::string::npos;
    if(legacy){auto j=json_parse(from_bytes(b64_decode(uri)));if(j.kind!=Json::Object)throw std::runtime_error("PARSE_INVALID: VMess payload must be object");for(const auto& p:j.object)q[lower(p.first)]=p.second.scalar();c.server=option(q,{"add","address"});check_host(c.server);c.port=uint16_t(number(option(q,{"port"}),1,65535));c.uuid=uuid_bytes(option(q,{"id"}));
        c.transport=transport_name(option(q,{"net","network"},"tcp"));auto tls=lower(trim(option(q,{"tls"})));c.security=(tls.empty()||tls=="none"||tls=="0"||tls=="false"||tls=="off")?(lower(option(q,{"security"}))=="tls"||lower(option(q,{"security"}))=="reality"?security_name(option(q,{"security"})):"none"):security_name(tls);
        if(q.count("scy"))c.cipher=q["scy"];else if(q.count("cipher"))c.cipher=q["cipher"];else if(q.count("security")&&lower(q["security"])!="tls"&&lower(q["security"])!="reality"&&lower(q["security"])!="none")c.cipher=q["security"];else c.cipher="auto";
        // Arrays are legitimate for legacy ALPN.
        if(j.at("alpn").kind==Json::Array){q["alpn"]="";for(const auto& x:j.at("alpn").array){auto v=trim(x.scalar());if(v.empty())continue;if(!q["alpn"].empty())q["alpn"]+=',';q["alpn"]+=v;}}
    }else{auto question=uri.find('?');if(question!=std::string::npos){raw_q=raw_uri_query(uri.substr(question+1));q=uri_query(uri.substr(question+1));uri.resize(question);}auto at=uri.rfind('@');std::string auth,hp;
        if(c.protocol=="ss"&&at==std::string::npos){auto decoded=from_bytes(b64_decode(uri));at=decoded.rfind('@');if(at==std::string::npos)throw std::runtime_error("PARSE_INVALID: Shadowsocks endpoint missing");auth=decoded.substr(0,at);hp=decoded.substr(at+1);}else{if(at==std::string::npos||at==0)throw std::runtime_error("PARSE_INVALID: missing credential");auth=uri.substr(0,at);hp=uri.substr(at+1);}
        endpoint(c,hp);
        if(c.protocol=="ss"){auth=uri_decode(auth);if(auth.find(':')==std::string::npos)auth=from_bytes(b64_decode(auth));auto colon=auth.find(':');if(colon==std::string::npos)throw std::runtime_error("PARSE_INVALID: missing Shadowsocks method");c.cipher=trim(auth.substr(0,colon));c.password=auth.substr(colon+1);if(c.password.empty())throw std::runtime_error("PARSE_INVALID: empty credential");}
        else{auto colon=auth.find(':');if(colon!=std::string::npos)auth.resize(colon);auth=uri_decode(auth);if(auth.empty())throw std::runtime_error("PARSE_INVALID: empty credential");if(c.protocol=="trojan")c.password_hash=sha224(auth);else c.uuid=uuid_bytes(trim(auth));}
        c.transport=transport_name(present(q,{"type","network","net"})?enum_field(raw_q,q,{"type","network","net"},true):true_value(option(q,{"ws"}))?"ws":"tcp");c.security=security_name(present(q,{"security","tls"})?enum_field(raw_q,q,{"security","tls"},false):c.protocol=="trojan"?"tls":"none");if(c.protocol=="vmess")c.cipher=option(q,{"encryption"},"auto");
    }
    c.original_options=q;c.flow=option(q,{"flow"});if(c.flow=="none")c.flow.clear();c.encryption=option(q,{"encryption"},"none");if(c.encryption.empty())c.encryption="none";c.fingerprint=option(q,{"fp","fingerprint","client-fingerprint"});c.path=option(q,{"path","wspath"},"/");c.host_header=option(q,{"host","authority"});c.authority=option(q,{"authority"},c.host_header);c.mode=option(q,{"mode"});c.header_type=option(q,{"headertype","header-type"},"none");if(legacy)c.header_type=option(q,{"type","headertype"},"none");
    c.service=option(q,{"servicename","service-name","grpc-service-name","service_name"});if(!present(q,{"servicename","service-name","grpc-service-name","service_name"})){c.service=c.path;auto a=c.service.find_first_not_of('/');c.service=a==std::string::npos?"":c.service.substr(a);}
    c.explicit_sni=present(q,{"sni","servername","server-name","peer"});c.tls_name=option(q,{"sni","servername","server-name","peer"},c.server);c.public_key=option(q,{"pbk","password","publickey","public-key"});c.short_id=option(q,{"sid","shortid","short-id"});c.spider_x=option(q,{"spx","spiderx"});c.ech=option(q,{"ech","echconfiglist","ech-config-list"});
    c.legacy_insecure_requested=true_value(option(q,{"allowinsecure","allow_insecure","allow-insecure","insecure","skip-cert-verify","skip_cert_verify"}));
    std::istringstream list(option(q,{"alpn"}));std::string p;while(std::getline(list,p,',')){p=trim(p);if(!p.empty()){if(p.size()>255)throw std::runtime_error("PARSE_INVALID: ALPN token too long");c.alpn.push_back(p);}}
    for(const auto& name:{"extra","fm","finalmask"})if(q.count(name)){Json v=optional_json(q[name],option(raw_q,{name}));if(std::string(name)=="extra")c.extra=v;else if(c.finalmask.kind==Json::Null)c.finalmask=v;}
    if(c.protocol=="vmess")c.alter_id=number(option(q,{"aid","alterid"},"0").empty()?"0":option(q,{"aid","alterid"},"0"),0,65535);
    parse_ss_plugin(c);
    if(c.transport=="websocket"){auto early=option(q,{"ed","max_early_data","maxearlydata","max-early-data"});auto query=c.path.find('?');if(query!=std::string::npos){auto path_options=uri_query(c.path.substr(query+1));if(early.empty()){early=option(path_options,{"ed"});if(!early.empty()&&early.find_first_not_of("0123456789")!=std::string::npos){early="";c.ws_path_ed_invalid=true;}}if(path_options.count("ed")){std::string rebuilt;std::istringstream items(c.path.substr(query+1));std::string item;while(std::getline(items,item,'&')){if(lower(uri_decode(item.substr(0,item.find('='))))=="ed")continue;if(!rebuilt.empty())rebuilt+='&';rebuilt+=item;}c.path.resize(query);if(!rebuilt.empty())c.path+='?'+rebuilt;}}if(!early.empty())c.ws_early_data=number(early,0,16384);c.ws_early_header=option(q,{"eh","earlydataheadername","early_data_header_name","early-data-header-name"},"Sec-WebSocket-Protocol");}
}
inline Config read_config(const std::string& path){std::ifstream f(std::filesystem::u8path(path),std::ios::binary);if(!f)throw std::runtime_error("PARSE_INVALID: cannot open config");f.seekg(0,std::ios::end);auto n=f.tellg();if(n<0||n>131072)throw std::runtime_error("PARSE_INVALID: config too large");f.seekg(0);std::string text((std::istreambuf_iterator<char>(f)),{});if(text.substr(0,3)=="\xef\xbb\xbf")text.erase(0,3);Options options;std::istringstream in(text);std::string line;while(std::getline(in,line)){line=trim(line);if(line.empty()||line[0]=='#'||line[0]==';')continue;auto eq=line.find('=');if(eq==std::string::npos)throw std::runtime_error("PARSE_INVALID: config requires key=value");if(!options.emplace(lower(trim(line.substr(0,eq))),trim(line.substr(eq+1))).second)throw std::runtime_error("PARSE_INVALID: duplicate config key");}if(!options.count("node_uri"))throw std::runtime_error("PARSE_INVALID: config missing node_uri");Config c;parse_uri(c,options["node_uri"]);for(const auto& p:options){if(p.first=="node_uri")continue;if(p.first=="listen_port")c.listen_port=uint16_t(number(p.second,0,65535));else if(p.first=="connect_timeout_ms")c.connect_ms=number(p.second,1000,120000);else if(p.first=="idle_timeout_ms")c.idle_ms=number(p.second,1000,600000);else if(p.first=="max_connections")c.max_connections=number(p.second,1,64);else if(p.first=="ready_file")c.ready_file=p.second;else if(p.first=="tls_ca_file")c.tls_ca_file=p.second;
#ifdef VPN_CORE_TEST_BACKEND
    else if(p.first=="test_ca_file")c.test_ca_file=p.second;
#endif
    else throw std::runtime_error("PARSE_INVALID: unknown config setting");}return c;}
}
