#pragma once
#include "protocol.hpp"
#include "huffman-table.hpp"

namespace vpn {
inline std::string huffman_decode(const Bytes& bytes){struct Node{int branch[2]{-1,-1};int symbol=-1;};static const auto trie=[](){std::vector<Node> tree(1);for(unsigned s=0;s<257;++s){int at=0;for(int bit=huffman_lengths[s]-1;bit>=0;--bit){auto x=(huffman_codes[s]>>bit)&1;int next=tree[size_t(at)].branch[x];if(next<0){next=int(tree.size());tree[size_t(at)].branch[x]=next;tree.emplace_back();}at=next;}tree[size_t(at)].symbol=int(s);}return tree;}();int at=0;unsigned pending=0,value=0;std::string out;for(auto byte:bytes)for(int bit=7;bit>=0;--bit){unsigned x=(byte>>bit)&1;value=(value<<1)|x;++pending;at=trie[size_t(at)].branch[x];if(at<0)throw std::runtime_error("TRANSPORT_FAILED: HPACK Huffman code");int s=trie[size_t(at)].symbol;if(s>=0){if(s==256)throw std::runtime_error("TRANSPORT_FAILED: HPACK Huffman EOS");out+=char(s);if(out.size()>65536)throw std::runtime_error("TRANSPORT_FAILED: HPACK string limit");at=0;pending=0;value=0;}}if(pending&&(pending>7||value!=((1u<<pending)-1)))throw std::runtime_error("TRANSPORT_FAILED: HPACK Huffman padding");return out;}
inline void hpack_integer(Bytes& out,size_t n,unsigned prefix,uint8_t flags){unsigned maximum=(1u<<prefix)-1;if(n<maximum){out.push_back(uint8_t(flags|n));return;}out.push_back(uint8_t(flags|maximum));n-=maximum;while(n>=128){out.push_back(uint8_t(n|128));n>>=7;}out.push_back(uint8_t(n));}
inline void hpack_string(Bytes& out,const std::string& s){hpack_integer(out,s.size(),7,0);append(out,to_bytes(s));}
inline void hpack_literal(Bytes& out,const std::string& key,const std::string& value){out.push_back(0);hpack_string(out,key);hpack_string(out,value);}
class Hpack {
    using Pair=std::pair<std::string,std::string>;std::vector<Pair> dynamic_;size_t maximum_=4096,size_=0;
    static const std::vector<Pair>& table(){static const std::vector<Pair> entries{{"",""},{":authority",""},{":method","GET"},{":method","POST"},{":path","/"},{":path","/index.html"},{":scheme","http"},{":scheme","https"},{":status","200"},{":status","204"},{":status","206"},{":status","304"},{":status","400"},{":status","404"},{":status","500"},{"accept-charset",""},{"accept-encoding","gzip, deflate"},{"accept-language",""},{"accept-ranges",""},{"accept",""},{"access-control-allow-origin",""},{"age",""},{"allow",""},{"authorization",""},{"cache-control",""},{"content-disposition",""},{"content-encoding",""},{"content-language",""},{"content-length",""},{"content-location",""},{"content-range",""},{"content-type",""},{"cookie",""},{"date",""},{"etag",""},{"expect",""},{"expires",""},{"from",""},{"host",""},{"if-match",""},{"if-modified-since",""},{"if-none-match",""},{"if-range",""},{"if-unmodified-since",""},{"last-modified",""},{"link",""},{"location",""},{"max-forwards",""},{"proxy-authenticate",""},{"proxy-authorization",""},{"range",""},{"referer",""},{"refresh",""},{"retry-after",""},{"server",""},{"set-cookie",""},{"strict-transport-security",""},{"transfer-encoding",""},{"user-agent",""},{"vary",""},{"via",""},{"www-authenticate",""}};return entries;}
    Pair indexed(size_t n){if(!n)throw std::runtime_error("TRANSPORT_FAILED: zero HPACK index");const auto& t=table();if(n<t.size())return t[n];n-=t.size();if(n>=dynamic_.size())throw std::runtime_error("TRANSPORT_FAILED: HPACK index bounds");return dynamic_[n];}
    static size_t integer(const Bytes& b,size_t& pos,unsigned prefix){if(pos==b.size())throw std::runtime_error("TRANSPORT_FAILED: truncated HPACK integer");unsigned max=(1u<<prefix)-1;size_t n=b[pos++]&max;if(n<max)return n;unsigned shift=0;for(;;){if(pos==b.size()||shift>21)throw std::runtime_error("TRANSPORT_FAILED: HPACK integer overflow");auto x=b[pos++];n+=size_t(x&127)<<shift;if(!(x&128))return n;shift+=7;}}
    static std::string string(const Bytes& b,size_t& pos){if(pos==b.size())throw std::runtime_error("TRANSPORT_FAILED: truncated HPACK string");bool huffman=(b[pos]&128)!=0;auto n=integer(b,pos,7);if(n>65536||n>b.size()-pos)throw std::runtime_error("TRANSPORT_FAILED: HPACK string length");Bytes value(b.begin()+std::ptrdiff_t(pos),b.begin()+std::ptrdiff_t(pos+n));pos+=n;return huffman?huffman_decode(value):from_bytes(value);}
    void evict(){while(size_>maximum_&&!dynamic_.empty()){size_-=dynamic_.back().first.size()+dynamic_.back().second.size()+32;dynamic_.pop_back();}}
public:
    std::vector<Pair> decode(const Bytes& b){size_t pos=0,total=0;std::vector<Pair> out;while(pos<b.size()){uint8_t x=b[pos];Pair p;if(x&128)p=indexed(integer(b,pos,7));else if((x&0xe0)==32){if(!out.empty())throw std::runtime_error("TRANSPORT_FAILED: misplaced HPACK size update");auto n=integer(b,pos,5);if(n>4096)throw std::runtime_error("TRANSPORT_FAILED: HPACK dynamic table limit");maximum_=n;evict();continue;}else{bool add=(x&64)!=0;auto name=integer(b,pos,add?6:4);p.first=name?indexed(name).first:string(b,pos);p.second=string(b,pos);if(add){dynamic_.insert(dynamic_.begin(),p);size_+=p.first.size()+p.second.size()+32;evict();}}total+=p.first.size()+p.second.size()+32;if(total>65536)throw std::runtime_error("TRANSPORT_FAILED: HTTP2 header list limit");out.push_back(std::move(p));}return out;}
};
}
