#pragma once
#include "hpack.hpp"
#include "http.hpp"
namespace vpn {
inline Bytes h2_frame(uint8_t type,uint8_t flags,uint32_t stream,const Bytes& payload){if(payload.size()>16777215)throw std::runtime_error("TRANSPORT_FAILED: HTTP2 frame size");Bytes b{uint8_t(payload.size()>>16),uint8_t(payload.size()>>8),uint8_t(payload.size()),type,flags};be32(b,stream);append(b,payload);return b;}
inline void protobuf_varint(Bytes& b,size_t n){while(n>=128){b.push_back(uint8_t(n|128));n>>=7;}b.push_back(uint8_t(n));}
inline size_t protobuf_integer(const Bytes& b,size_t& p){size_t n=0;for(unsigned shift=0;shift<=28;shift+=7){if(p==b.size())break;auto x=b[p++];n|=size_t(x&127)<<shift;if(!(x&128))return n;}throw std::runtime_error("TRANSPORT_FAILED: protobuf integer");}
class Http2 {
    Bytes input_,headers_,messages_,pending_,control_;size_t pending_offset_=0;Hpack hpack_;int64_t connection_window_=65535,stream_window_=65535,initial_window_=65535;size_t maximum_frame_=16384;bool settings_seen_=false,headers_seen_=false,continuation_=false,header_end_stream_=false,closed_=false,ending_=false,end_sent_=false,multi_=false,xhttp_=false;std::string content_type_;bool status_ok_=false;
    Bytes drain(){Bytes out;while(pending_offset_<pending_.size()&&connection_window_>0&&stream_window_>0){auto n=std::min({pending_.size()-pending_offset_,maximum_frame_,size_t(connection_window_),size_t(stream_window_)});Bytes body(pending_.begin()+std::ptrdiff_t(pending_offset_),pending_.begin()+std::ptrdiff_t(pending_offset_+n));append(out,h2_frame(0,0,1,body));pending_offset_+=n;connection_window_-=int64_t(n);stream_window_-=int64_t(n);}if(pending_offset_==pending_.size()){pending_.clear();pending_offset_=0;if(ending_&&!end_sent_){append(out,h2_frame(0,1,1,{}));end_sent_=true;}}return out;}
    void decode_headers(){auto fields=hpack_.decode(headers_);headers_.clear();bool grpc_status=false;for(const auto& p:fields){if(p.first==":status"){unsigned status=0;if(p.second.size()==3&&p.second.find_first_not_of("0123456789")==std::string::npos)status=number(p.second,100,599);if(headers_seen_||p.second!="200")throw Failure("TRANSPORT_FAILED: HTTP2 response status","HTTP2_STATUS",0,status);status_ok_=true;}else if(p.first=="content-type")content_type_=p.second;else if(p.first=="content-encoding"&&p.second!="identity")throw Failure("TRANSPORT_FAILED: HTTP content encoding","HTTP_CONTENT_ENCODING");else if(!xhttp_&&p.first=="grpc-status"){grpc_status=true;if(p.second!="0")throw std::runtime_error("TRANSPORT_FAILED: remote gRPC status");}else if(!xhttp_&&p.first=="grpc-encoding"&&p.second!="identity")throw std::runtime_error("FEATURE_UNIMPLEMENTED: gRPC compression");}
        if(!headers_seen_){if(!status_ok_||(!xhttp_&&content_type_.find("application/grpc")!=0))throw std::runtime_error("TRANSPORT_FAILED: HTTP2 response headers");headers_seen_=true;}if(header_end_stream_){if(!xhttp_&&!grpc_status)throw std::runtime_error("TRANSPORT_FAILED: missing gRPC trailer status");if(!messages_.empty())throw std::runtime_error("TRANSPORT_FAILED: incomplete gRPC message");closed_=true;}}
    Bytes decode_messages(){Bytes out;for(;;){if(messages_.size()<5)break;if(messages_[0])throw std::runtime_error("FEATURE_UNIMPLEMENTED: compressed gRPC message");auto n=get32(messages_,1);if(n>524288)throw std::runtime_error("TRANSPORT_FAILED: gRPC message limit");if(messages_.size()<size_t(n)+5)break;consume(messages_,5);auto body=consume(messages_,n);Bytes data;size_t p=0;while(p<body.size()){auto tag=protobuf_integer(body,p);size_t field=tag>>3,wire=tag&7;if(!field)throw std::runtime_error("TRANSPORT_FAILED: protobuf field zero");if(wire==2){auto length=protobuf_integer(body,p);if(length>body.size()-p)throw std::runtime_error("TRANSPORT_FAILED: protobuf length");if(field==1){if(!multi_)data.clear();data.insert(data.end(),body.begin()+std::ptrdiff_t(p),body.begin()+std::ptrdiff_t(p+length));}p+=length;}else if(wire==0){protobuf_integer(body,p);}else if(wire==1||wire==5){auto count=wire==1?8u:4u;if(count>body.size()-p)throw std::runtime_error("TRANSPORT_FAILED: protobuf fixed length");p+=count;}else throw std::runtime_error("TRANSPORT_FAILED: protobuf wire type");}append(out,data);}return out;}
public:
    Bytes open(const Config& c){xhttp_=c.transport=="xhttp";multi_=lower(c.mode)=="multi"||lower(c.mode)=="multi-mode"||lower(c.mode)=="multimode";auto escape=[](const std::string& value){std::string out;const char* h="0123456789ABCDEF";for(unsigned char x:value){if((x>='a'&&x<='z')||(x>='A'&&x<='Z')||(x>='0'&&x<='9')||std::string("-_.~:@&=+$").find(char(x))!=std::string::npos)out+=char(x);else{out+='%';out+=h[x>>4];out+=h[x&15];}}return out;};
        auto service=escape(c.service);auto method=multi_?std::string("TunMulti"):std::string("Tun");if(!c.service.empty()&&c.service[0]=='/'){auto last=c.service.rfind('/');service="";std::istringstream parts(c.service.substr(1,last>0?last-1:0));std::string part;while(std::getline(parts,part,'/')){if(!service.empty())service+='/';service+=escape(part);}auto tail=c.service.substr(last+1);auto bar=tail.find('|');method=escape(multi_&&bar!=std::string::npos?tail.substr(bar+1):tail.substr(0,bar));}Bytes headers;hpack_literal(headers,":method","POST");hpack_literal(headers,":scheme",c.security=="tls"?"https":"http");hpack_literal(headers,":path",xhttp_?http_path(c,true):"/"+service+"/"+method);hpack_literal(headers,":authority",xhttp_?http_host(c):c.authority.empty()?c.server+":"+std::to_string(c.port):c.authority);if(xhttp_){for(const auto& p:xhttp_headers(c))hpack_literal(headers,p.first,p.second);}else{hpack_literal(headers,"content-type","application/grpc");hpack_literal(headers,"te","trailers");hpack_literal(headers,"grpc-accept-encoding","identity");}Bytes settings;be16(settings,2);be32(settings,0);be16(settings,4);be32(settings,1048576);be16(settings,6);be32(settings,65536);Bytes out=to_bytes("PRI * HTTP/2.0\r\n\r\nSM\r\n\r\n");append(out,h2_frame(4,0,0,settings));Bytes window;be32(window,1048576-65535);append(out,h2_frame(8,0,0,window));append(out,h2_frame(1,4,1,headers));return out;}
    size_t pending_bytes()const{return pending_.size()-pending_offset_;}
    Bytes encode(const Bytes& b){if(ending_)throw std::runtime_error("TRANSPORT_FAILED: HTTP2 write after EOF");if(pending_offset_){pending_.erase(pending_.begin(),pending_.begin()+std::ptrdiff_t(pending_offset_));pending_offset_=0;}if(xhttp_)append(pending_,b);else{Bytes message{10};protobuf_varint(message,b.size());append(message,b);pending_.push_back(0);be32(pending_,uint32_t(message.size()));append(pending_,message);}if(pending_.size()>1048576)throw std::runtime_error("TRANSPORT_FAILED: HTTP2 pending buffer limit");return drain();}
    Bytes finish(){ending_=true;return drain();}
    bool closed()const{return closed_;}
    Bytes control(){auto b=std::exchange(control_,{});append(b,drain());return b;}
    Bytes decode(const Bytes& incoming){append(input_,incoming);if(input_.size()>1048576)throw std::runtime_error("TRANSPORT_FAILED: HTTP2 input limit");Bytes out;for(;;){if(input_.size()<9)break;size_t n=(size_t(input_[0])<<16)|(size_t(input_[1])<<8)|input_[2];uint8_t type=input_[3],flags=input_[4];uint32_t stream=get32(input_,5)&0x7fffffff;if(n>16384)throw std::runtime_error("TRANSPORT_FAILED: peer exceeded HTTP2 frame limit");if(input_.size()<n+9)break;consume(input_,9);auto payload=consume(input_,n);if(!settings_seen_&&(type!=4||stream!=0||(flags&1)))throw std::runtime_error("TRANSPORT_FAILED: HTTP2 first frame must be SETTINGS");if(continuation_&&(type!=9||stream!=1))throw std::runtime_error("TRANSPORT_FAILED: interleaved HTTP2 header block");
        if(type==4){if(stream||((flags&1)&&n)||n%6)throw std::runtime_error("TRANSPORT_FAILED: malformed HTTP2 settings");settings_seen_=true;if(!(flags&1)){for(size_t p=0;p<n;p+=6){auto key=get16(payload,p);auto value=get32(payload,p+2);if(key==4){if(value>0x7fffffff)throw std::runtime_error("TRANSPORT_FAILED: HTTP2 initial window overflow");stream_window_+=int64_t(value)-initial_window_;initial_window_=value;}else if(key==5){if(value<16384||value>16777215)throw std::runtime_error("TRANSPORT_FAILED: HTTP2 max frame setting");maximum_frame_=std::min(size_t(value),size_t(65536));}}append(control_,h2_frame(4,1,0,{}));}}
        else if(type==8){if(n!=4)throw std::runtime_error("TRANSPORT_FAILED: HTTP2 window frame length");auto increment=get32(payload)&0x7fffffff;if(!increment)throw std::runtime_error("TRANSPORT_FAILED: HTTP2 zero window increment");auto& window=stream==0?connection_window_:stream_window_;if(stream>1)throw std::runtime_error("TRANSPORT_FAILED: unexpected HTTP2 stream");if(window+increment>0x7fffffff)throw std::runtime_error("TRANSPORT_FAILED: HTTP2 window overflow");window+=increment;}
        else if(type==6){if(stream||n!=8)throw std::runtime_error("TRANSPORT_FAILED: malformed HTTP2 ping");if(!(flags&1))append(control_,h2_frame(6,1,0,payload));}
        else if(type==1||type==9){if(stream!=1)throw std::runtime_error("TRANSPORT_FAILED: unexpected HTTP2 headers stream");size_t start=0,end=n;if(type==1){if(continuation_)throw std::runtime_error("TRANSPORT_FAILED: nested HTTP2 headers");header_end_stream_=(flags&1)!=0;if(flags&8){if(!n||payload[0]>=n)throw std::runtime_error("TRANSPORT_FAILED: HTTP2 header padding");start=1;end-=payload[0];}if(flags&32)start+=5;}if(start>end)throw std::runtime_error("TRANSPORT_FAILED: HTTP2 header prefix");headers_.insert(headers_.end(),payload.begin()+std::ptrdiff_t(start),payload.begin()+std::ptrdiff_t(end));if(headers_.size()>65536)throw std::runtime_error("TRANSPORT_FAILED: HTTP2 header block limit");continuation_=(flags&4)==0;if(!continuation_)decode_headers();}
        else if(type==0){if(stream!=1||!headers_seen_||closed_)throw std::runtime_error("TRANSPORT_FAILED: unexpected HTTP2 DATA");size_t start=0,end=n;if(flags&8){if(!n||payload[0]>=n)throw std::runtime_error("TRANSPORT_FAILED: HTTP2 data padding");start=1;end-=payload[0];}if(xhttp_)out.insert(out.end(),payload.begin()+std::ptrdiff_t(start),payload.begin()+std::ptrdiff_t(end));else{messages_.insert(messages_.end(),payload.begin()+std::ptrdiff_t(start),payload.begin()+std::ptrdiff_t(end));append(out,decode_messages());}if(n){Bytes window;be32(window,uint32_t(n));append(control_,h2_frame(8,0,0,window));append(control_,h2_frame(8,0,1,window));}if(flags&1){if(xhttp_)closed_=true;else{if(!messages_.empty())throw std::runtime_error("TRANSPORT_FAILED: incomplete gRPC message");throw std::runtime_error("TRANSPORT_FAILED: gRPC DATA ended without trailers");}}}
        else if(type==3){if(stream!=1||n!=4)throw std::runtime_error("TRANSPORT_FAILED: HTTP2 reset frame");throw std::runtime_error("TRANSPORT_FAILED: remote HTTP2 stream reset");}
        else if(type==7){if(stream||n<8)throw std::runtime_error("TRANSPORT_FAILED: HTTP2 GOAWAY length");if(get32(payload,4))throw std::runtime_error("TRANSPORT_FAILED: HTTP2 GOAWAY error");}
        else if(type==5)throw std::runtime_error("TRANSPORT_FAILED: unsolicited HTTP2 push");
    }return out;}
};
}
