#pragma once
#include "tls-provider.hpp"
namespace vpn {
struct XHttpAPI {
    int(*validate)(char*,int)=nullptr;uint64_t(*create)(char*,int,char*,int)=nullptr;int(*write)(uint64_t,char*,int)=nullptr;int(*read)(uint64_t,char*,int)=nullptr;int(*state)(uint64_t)=nullptr;int(*info)(uint64_t,char*,int)=nullptr;int(*pending)(uint64_t)=nullptr;int(*finish)(uint64_t)=nullptr;void(*free)(uint64_t)=nullptr;
    XHttpAPI(){auto& api=TlsProviderAPI::instance();api.symbol(validate,"vpn_xhttp_validate");api.symbol(create,"vpn_xhttp_new");api.symbol(write,"vpn_xhttp_write");api.symbol(read,"vpn_xhttp_read");api.symbol(state,"vpn_xhttp_state");api.symbol(info,"vpn_xhttp_info");api.symbol(pending,"vpn_xhttp_pending");api.symbol(finish,"vpn_xhttp_finish");api.symbol(free,"vpn_xhttp_free");}
    static XHttpAPI& instance(){static XHttpAPI api;return api;}
};
inline Json xhttp_provider_settings(const Config& c){Json settings=Json::obj();settings["transport"]=Json(c.transport);settings["kcp"]=Json::obj();if(c.transport=="kcp"){auto& kcp=settings["kcp"];kcp["header"]=Json(c.header_type);kcp["header_domain"]=Json(option(c.original_options,{"headerdomain","header-domain"}));if(c.original_options.count("seed"))kcp["seed"]=Json(c.original_options.at("seed"));for(const auto& key:{"mtu","tti"})if(c.original_options.count(key))kcp[key]=Json::integer(number(c.original_options.at(key),1,65535));}settings["quic"]=Json::obj();if(c.transport=="quic"){auto& q=settings["quic"];q["header"]=Json(c.header_type);q["header_domain"]=Json(option(c.original_options,{"headerdomain","header-domain"}));q["cipher"]=Json(c.ss_plugin=="v2ray-plugin"?"none":option(c.original_options,{"quicsecurity","quic-security"},"none"));q["key"]=Json(option(c.original_options,{"quickey","quic-key","key"}));}settings["server"]=Json(c.server);settings["port"]=Json::integer(c.port);settings["host"]=Json(c.host_header);settings["path"]=Json(c.path);settings["mode"]=Json(c.mode);settings["legacy_http"]=Json::boolean(c.transport=="http");settings["extra"]=c.extra;settings["tls"]=provider_settings(c);settings["masks"]=Json::arr();auto range=[](const MaskRange& value){Json out=Json::obj();out["Lo"]=Json::integer(value.lo);out["Hi"]=Json::integer(value.hi);return out;};for(const auto& spec:fragment_specs(c.finalmask)){Json mask=Json::obj();mask["tlshello"]=Json::boolean(spec.tlshello);mask["Packets"]=range(spec.packets);mask["MaxSplit"]=range(spec.max_split);mask["Lengths"]=Json::arr();mask["Delays"]=Json::arr();for(const auto& r:spec.lengths)mask["Lengths"].array.push_back(range(r));for(const auto& r:spec.delays)mask["Delays"].array.push_back(range(r));settings["masks"].array.push_back(mask);}return settings;}
inline void validate_xhttp_configuration(const Config& c){auto text=json_dump(xhttp_provider_settings(c));int status=XHttpAPI::instance().validate(text.data(),int(text.size()));if(status)throw Failure("PARSE_INVALID: invalid XHTTP configuration","XHTTP_CONFIGURATION");}
class XHttpStream {
    XHttpAPI& api_=XHttpAPI::instance();uint64_t id_=0;size_t write_offset_=0;
    void check(){auto status=api_.state(id_);if(status>=0)return;unsigned http=0;char buffer[1024];auto n=api_.info(id_,buffer,sizeof(buffer));if(n>0){auto j=json_parse(std::string(buffer,size_t(n)));auto value=j.at("http_status").scalar();if(!value.empty())http=number(value,0,599);}int code=-status;throw Failure(code>=300&&code<400?"TLS_FAILED: XHTTP TLS authentication failed":"TRANSPORT_FAILED: XHTTP request failed",code==400?"XHTTP_CONFIGURATION":code==402?"XHTTP_CONNECT":code==403?"ALPN_XHTTP":code==404?"XHTTP_HTTP_STATUS":code==405?"HTTP_CONTENT_ENCODING":code==406?"XHTTP_HEADER_LIMIT":code==407?"FINALMASK_LIMIT":code>=300&&code<400?tls_provider_reason(code):"XHTTP_IO",uint32_t(code),http);}
public:
    XHttpStream()=default;XHttpStream(const XHttpStream&)=delete;XHttpStream& operator=(const XHttpStream&)=delete;~XHttpStream(){if(id_)api_.free(id_);}
    void open(const Config& c,const Bytes& header,Clock::time_point deadline){auto settings=xhttp_provider_settings(c);auto text=json_dump(settings);id_=api_.create(text.data(),int(text.size()),reinterpret_cast<char*>(const_cast<uint8_t*>(header.data())),int(header.size()));if(!id_)throw Failure("TRANSPORT_FAILED: XHTTP initialization","XHTTP_CREATE");while(api_.state(id_)==0){if(Clock::now()>=deadline)throw Failure("TRANSPORT_FAILED: XHTTP connect timeout","XHTTP_TIMEOUT");std::this_thread::sleep_for(std::chrono::milliseconds(1));}check();}
    Bytes read(){check();char data[65536];int n=api_.read(id_,data,sizeof(data));if(n<0)throw Failure("TRANSPORT_FAILED: XHTTP read","XHTTP_READ");return Bytes(reinterpret_cast<uint8_t*>(data),reinterpret_cast<uint8_t*>(data)+n);}
    bool write(const Bytes& data){check();while(write_offset_<data.size()){auto count=std::min(size_t(65536),data.size()-write_offset_);auto n=api_.write(id_,reinterpret_cast<char*>(const_cast<uint8_t*>(data.data()+write_offset_)),int(count));if(n<0){check();throw Failure("TRANSPORT_FAILED: XHTTP write after end","XHTTP_WRITE");}if(!n)return false;write_offset_+=size_t(n);}write_offset_=0;return true;}
    void finish(){check();if(api_.finish(id_)<0)throw Failure("TRANSPORT_FAILED: XHTTP EOF","XHTTP_EOF");}
    bool closed(){check();return api_.state(id_)==2;}
    size_t pending(){check();auto n=api_.pending(id_);return n<0?0:size_t(n);}
    Json metadata(){char data[1024];auto n=api_.info(id_,data,sizeof(data));if(n<=0)return Json::obj();return json_parse(std::string(data,size_t(n)));}
};
}
