name: Windows Pre Node Test
on:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  source_build_and_test:
    permissions:
      contents: write
    uses: ./.github/workflows/core-validation.yml
    with:
      full_network: true
